version: '3.7'

services:
  mysql:
    container_name: projetobase-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=projeto_base
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - projeto_base

networks:
  projeto_base: