mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: projeto_base
  url:  ${DATABASE_MYSQL_PASSWORD:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
